# -*- coding: utf-8 -*-
"""suc_turboquant-gpui.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ei4c5wrJdZUGm7WVbeeIuUTY__2vin90

# turboquant-gpu

5.02x KV cache compression for LLM inference using cuTile kernels with PyTorch fallback.

Paper: [TurboQuant](https://arxiv.org/abs/2501.09747) (ICLR 2026)

## install

Detects your CUDA driver version and installs a compatible PyTorch wheel. Also installs `cuda-tile` for GPU kernel acceleration (falls back to PyTorch if unavailable). Restart the kernel after this cell finishes.
"""

import subprocess, sys, ctypes

def pip(*args):
    subprocess.run([sys.executable, "-m", "pip", "install", *args], check=True)

subprocess.run([sys.executable, "-m", "ensurepip", "--upgrade"],
               capture_output=True)

try:
    libcuda = ctypes.CDLL("libcuda.so.1")
    v = ctypes.c_int()
    libcuda.cuInit(0)
    libcuda.cuDriverGetVersion(ctypes.byref(v))
    drv = v.value
except Exception:
    drv = 0

if   drv >= 12800: whl = "cu128"
elif drv >= 12400: whl = "cu124"
elif drv >= 12100: whl = "cu121"
else:              whl = "cu118"

print(f"CUDA driver {drv} -> pytorch {whl}")
pip("torch", "--index-url", f"https://download.pytorch.org/whl/{whl}", "--force-reinstall")

try:
    pip("cuda-tile[tileiras]", "--extra-index-url", "https://pypi.nvidia.com")
except Exception:
    print("cuda-tile not available, will use pytorch fallback")

pip("turboquant-gpu")
pip("scipy", "transformers", "accelerate", "sentencepiece")
print("\ndone. restart kernel then run next cell.")

"""## setup

Import the engine and detect the GPU. If no CUDA device is found, everything runs on CPU with PyTorch fallback.
"""

import torch, time
from turboquant_gpu import TurboQuantEngine
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    gpu = torch.cuda.get_device_name()
    sm  = torch.cuda.get_device_capability()
    print(f"{gpu}  |  sm_{sm[0]}{sm[1]}  |  CUDA {torch.version.cuda}")
else:
    print("no GPU, running on CPU")

"""## load model

Load Mistral 7B in FP16. The `TurboQuantEngine` takes `head_dim` (128 for Mistral) and `total_bits=3` which gives 2-bit key MSE + 1-bit QJL correction, and 3-bit value quantization.
"""

model_id = "mistralai/Mistral-7B-v0.1"

tok   = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id, torch_dtype=torch.float16, device_map=device)

head_dim = model.config.hidden_size // model.config.num_attention_heads
engine   = TurboQuantEngine(head_dim=head_dim, total_bits=3, device=device)
print(f"head_dim={head_dim}  |  device={device}")

"""## generate with compressed KV cache

One call does everything: prefill, compress the KV cache to 3 bits, rebuild a `DynamicCache`, and decode autoregressively. The compression ratio and generation time are printed at the end.
"""

t0 = time.time()
out = engine.generate(model, tok, "The University of Waterloo is known for ")
t1 = time.time()

print(out["text"])
print(f"\n{out['tokens']} tokens  |  {out['stats']['ratio']:.2f}x compression  |  {t1-t0:.2f}s")

"""## auto-tune

Benchmarks all combinations of bit-width (2 vs 3) and backend (cuTile vs PyTorch) on your specific GPU. Picks the fastest configuration that passes a cosine similarity quality threshold. After this, the engine uses the winning config for all subsequent calls.
"""

engine.auto_tune(seq_len=512)

"""## generate again (after auto-tune)

Same prompt, same model, but now using whatever config auto-tune selected. Compare the timing and compression ratio to the run above.
"""

t0 = time.time()
out = engine.generate(model, tok, "The University of Waterloo is known for ")
t1 = time.time()

print(out["text"])
print(f"\n{out['tokens']} tokens  |  {out['stats']['ratio']:.2f}x compression  |  {t1-t0:.2f}s (after auto-tune)")







"""### شغال

https://github.com/DevTechJr/turboquant-gpu/tree/main
"""

!pip install turboquant-gpu

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "Napoleon Bonaparte is ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=1, device="cuda")
result = engine.generate(model, tok, "ai is ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=1, device="cuda")
result = engine.generate(model, tok, "what is llm ?")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen3.5-4B"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

!pip list

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen2.5-3B-Instruct"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "what is python ?")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

engine = TurboQuantEngine(head_dim=128, total_bits=1, device="cuda")
result = engine.generate(model, tok, "what is llm ?")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

engine = TurboQuantEngine(head_dim=128, total_bits=1, device="cuda")
result = engine.generate(model, tok, "what is google ?")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen3.5-2B"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

!pip install git+https://github.com/huggingface/transformers.git

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen3.5-2B"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

"""`torch_dtype` is deprecated! Use `dtype` instead!
model.safetensors.index.json:
 64.5k/? [00:00<00:00, 1.59MB/s]
model.safetensors-00001-of-00001.safeten(…): 100%
 4.55G/4.55G [00:55<00:00, 87.4MB/s]
The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d
Loading weights: 100%
 320/320 [00:14<00:00, 26.23it/s]
tokenizer_config.json:
 16.7k/? [00:00<00:00, 1.18MB/s]
tokenizer.json: 100%
 12.8M/12.8M [00:01<00:00, 37.5MB/s]
chat_template.jinja:
 7.75k/? [00:00<00:00, 434kB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.12/dist-packages/turboquant_gpu/host.py in _extract_kv(past_key_values)
    267         try:
--> 268             return past_key_values.key_cache, past_key_values.value_cache
    269         except AttributeError:

AttributeError: 'DynamicCache' object has no attribute 'key_cache'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
6 frames
/usr/local/lib/python3.12/dist-packages/transformers/cache_utils.py in __iter__(self)
   1287     def __iter__(self):
   1288         for layer in self.layers:
-> 1289             yield layer.keys, layer.values, getattr(layer, "_sliding_window_tensor", None)
   1290
   1291

AttributeError: 'LinearAttentionLayer' object has no attribute 'keys'

"""

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen3.5-2B"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen3.5-2B"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")

# one-call generation
result = engine.generate(model, tok, "hi")

# step-by-step
compressed = engine.compress_kv_cache(out.past_key_values)
cache      = engine.build_cache(compressed)
stats      = engine.compression_stats(out.past_key_values)

# auto-tune for your GPU (benchmarks cutile vs pytorch, 2-bit vs 3-bit)
engine.auto_tune(seq_len=512)

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "google/translategemma-4b-it"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "translate into arabic The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")



"""# https://pypi.org/project/turboquant-gpu/"""



from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "Qwen/Qwen3-ASR-1.7B"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "translate into arabic The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")

!pip install transformers==5.4

!pip show transformers

from transformers import AutoModelForCausalLM, AutoTokenizer
from turboquant_gpu import TurboQuantEngine
import torch

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="cuda")
tok   = AutoTokenizer.from_pretrained(model_id)

engine = TurboQuantEngine(head_dim=128, total_bits=3, device="cuda")
result = engine.generate(model, tok, "translate into arabic The University of Waterloo is known for ")

print(result["text"])
print(f"{result['tokens']} tokens | {result['stats']['ratio']:.2f}x compression")